name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add hub https://DESMOND135:$HF_TOKEN@huggingface.co/spaces/DESMOND135/DESMOND_LANGCHAIN_CHAT_WITH_SEARCH
          git fetch hub
          git pull hub main --allow-unrelated-histories
          git push hub main
